# Generated by Django 4.2.3 on 2023-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field=480, upload_to='', width_field=480)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('style', models.ManyToManyField(default='NA', related_name='image_cards', to='Gallery.stylecategory')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
