# Generated by Django 4.2.3 on 2023-07-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='static/'),
        ),
    ]
