# Generated by Django 4.2.3 on 2023-07-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StyleCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='imagecard',
            old_name='style',
            new_name='category',
        ),
    ]
