# Generated by Django 4.2.3 on 2023-07-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_rename_stylecategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecard',
            name='title',
            field=models.CharField(default='the_title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.ImageField(height_field=360, upload_to='Gallery/images', width_field=480),
        ),
    ]
