# Generated by Django 4.2.3 on 2023-07-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_imagecard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
