# Generated by Django 4.2.3 on 2023-07-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_imagecard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery/images'),
        ),
    ]
