# Generated by Django 4.2.3 on 2023-07-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_imagecard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.ImageField(height_field='height', upload_to='Gallery/images', width_field='width'),
        ),
    ]
