# Generated by Django 4.2.3 on 2023-08-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0007_alter_imagecard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecard',
            old_name='category',
            new_name='categories',
        ),
    ]
