# Generated by Django 4.2.3 on 2023-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0007_alter_imagecard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='imagecard',
            name='title',
        ),
        migrations.AddField(
            model_name='imagecard',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/Gallery/images'),
        ),
    ]
