# Generated by Django 4.2.3 on 2023-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_rename_category_imagecard_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body_text', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='ImageCard',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='categories',
            field=models.ManyToManyField(default='NA', related_name='gallery_item', to='Gallery.gallerycategory'),
        ),
    ]
